OK = 0
PREMISSION_DENIED = 101
INTERNAL_ERROR = 102
NOT_IMPLEMENTED = 103
INVALID_ARGUMENTS = 104
PASSWORD_MISMATCH = 105
PASSWORD_WRONG_TOO_MUCH = 106
USER_EXIST = 107
USER_NON_EXIST = 108
SUPERVISION_EXIST = 109
SUPERVISION_NON_EXIST = 110
SUPERVISION_EXPIRED = 111
IDEA_EXIST = 112
IDEA_NON_EXIST = 113
IDEA_LOCKED = 114
GROUP_EXIST = 115
GROUP_NON_EXIST = 116

MSG = {
    OK: "ok",
    PREMISSION_DENIED: "权限不足",
    INTERNAL_ERROR: "内部错误",
    NOT_IMPLEMENTED: "未实现",
    INVALID_ARGUMENTS: "传入参数错误",
    PASSWORD_MISMATCH: "用户名或密码错误",
    PASSWORD_WRONG_TOO_MUCH: "多次密码错误，请稍后再试",
    USER_EXIST: "用户已存在",
    USER_NON_EXIST: "用户不存在",
    SUPERVISION_EXIST: "监督已存在",
    SUPERVISION_NON_EXIST: "监督不存在",
    SUPERVISION_EXPIRED: "监督已过期",
    IDEA_EXIST: "意见已存在",
    IDEA_NON_EXIST: "意见不存在",
    IDEA_LOCKED: "意见已处理完成",
    GROUP_EXIST: "用户组已存在",
    GROUP_NON_EXIST: "用户组不存在",
}
